---

- name: check for required variables
  ansible.builtin.assert:
    that:
      - env_files_path

- name: package
  import_tasks: package.yml

- name: configure
  import_tasks: configure.yml

- name: aliases
  import_tasks: aliases.yml
