---
# This is an example playbook to execute Ansible tests.

- name: Verify
  hosts: all
  gather_facts: true
  vars:
    git_name: Jane Doe
    git_email: jane@example.com
  tasks:
    - name: Example assertion
      ansible.builtin.assert:
        that: true
